"""Authentication package providing domain models, hexagonal ports, and OIDC client."""

from .dependencies import (
    AdminUserDep,
    AuthAdapterDep,
    AuthenticatedUserDep,
    CurrentIdentityDep,
    get_auth_adapter,
    get_current_identity,
    require_admin,
    require_authenticated,
    require_group,
    set_auth_adapter,
)
from .oidc import (
    InvalidNonceError,
    InvalidStateError,
    OIDCAuthAdapter,
    OIDCClient,
    OIDCConfig,
    OIDCDiscovery,
    OIDCError,
    OIDCTransaction,
    SessionRecord,
    TokenValidationError,
    claims_to_identity,
    extract_identity_from_claims,
    generate_code_challenge,
    generate_code_verifier,
    generate_nonce,
    generate_state,
    resolve_claim_path,
)
from .port import AuthPort, Identity

__all__ = [
    "AdminUserDep",
    "AuthAdapterDep",
    "AuthPort",
    "AuthenticatedUserDep",
    "CurrentIdentityDep",
    "Identity",
    "InvalidNonceError",
    "InvalidStateError",
    "OIDCAuthAdapter",
    "OIDCClient",
    "OIDCConfig",
    "OIDCDiscovery",
    "OIDCError",
    "OIDCTransaction",
    "SessionRecord",
    "TokenValidationError",
    "claims_to_identity",
    "extract_identity_from_claims",
    "generate_code_challenge",
    "generate_code_verifier",
    "generate_nonce",
    "generate_state",
    "get_auth_adapter",
    "get_current_identity",
    "require_admin",
    "require_authenticated",
    "require_group",
    "resolve_claim_path",
    "set_auth_adapter",
]
